apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    biuldurl: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
