apiVersion: v1
kind: Pod
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    resource:
      request:
        memory: "68mi"
        cpu: "100m"
      limits:
        memory: "120mi"
        cpu: "150m"