apiVersion: v1
kind: Service
metadata:
  name: my-services
spec:
  selector:
    environment: dev
    project: expence
    component: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    environment: dev
    project: expence
    component: backend
spec:
  containers:
  - name: nginx
    image: nginx