apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    environment: dev
    project: expence
    component: backend
    version: "1.0.0"
    demo: np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-np
  labels:
    environment: dev
    project: expence
    component: backend
    version: "1.0.0"
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx
