apiVersion: v1
kind: Service
metadata:
  name: sercice-lb
spec:
  type: LoadBalancer
  selector:
    environment: dev
    project: expence
    component: backend
    version: "1.0.0"
    demo: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30017
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-lb
  lables:
    environment: dev
    project: expence
    component: backend
    version: "1.0.0"
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx

